name: 🚀 lineicons release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: 🚀 lineicons release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4

      - name: 🟢 setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: installing packages
        run: npm ci

      - name: 📦 build
        run: npm run build --if-present

      - name: 🚀 publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
